# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-06-11 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edxucursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edxucursostokens',
            name='user',
        ),
        migrations.DeleteModel(
            name='EdxUCursosTokens',
        ),
    ]
